import { DrugTemplate, ClinicSettings, DiagnosisTemplate } from './types';

export const INITIAL_DRUGS: DrugTemplate[] = [
  { id: 'man-1', name: 'Syringe', defaultStrength: '5ml', defaultInstructions: 'As directed', category: 'Equipment' },
  { id: 'man-2', name: 'Syringe', defaultStrength: '10ml', defaultInstructions: 'As directed', category: 'Equipment' },
  { id: 'man-3', name: 'IV Canula', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Equipment' },
  { id: 'man-4', name: 'Knife', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Equipment' },
  { id: 'man-5', name: 'Tab levosulpirid', defaultStrength: '50mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-6', name: 'Amp Decadron', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Ampule' },
  { id: 'man-7', name: 'Tab levosulpiride', defaultStrength: '25mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-8', name: 'Syringe insulin', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Equipment' },
  { id: 'man-9', name: 'Set Serum', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Equipment' },
  { id: 'man-10', name: 'Syp Digy AT', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Syrup' },
  { id: 'man-11', name: 'Amp gecobalamin', defaultStrength: '500mg', defaultInstructions: 'As directed', category: 'Ampule' },
  { id: 'man-12', name: 'Amp Vitamin C', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Ampule' },
  { id: 'man-13', name: 'Cap Digest -pro', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Capsule' },
  { id: 'man-14', name: 'Gauze Pad', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Equipment' },
  { id: 'man-15', name: 'Tab domflash oro', defaultStrength: '10mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-16', name: 'Tab Olanzapine', defaultStrength: '5mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-17', name: 'Syp Flagyl', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Syrup' },
  { id: 'man-18', name: 'Syp AKAM -CID', defaultStrength: '240ml', defaultInstructions: 'As directed', category: 'Syrup' },
  { id: 'man-19', name: 'Tab Pento life', defaultStrength: '40mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-20', name: 'Mask', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Equipment' },
  { id: 'man-21', name: 'Pregnacy test', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Equipment' },
  { id: 'man-22', name: 'Tab ponstan', defaultStrength: '250mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-23', name: 'Tab cold', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-24', name: 'Tab Stemetil', defaultStrength: '5mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-25', name: 'Tab Bisacodyl', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-26', name: 'Cap Eso A', defaultStrength: '40mg', defaultInstructions: 'As directed', category: 'Capsule' },
  { id: 'man-27', name: 'Amp Nospa', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Ampule' },
  { id: 'man-28', name: 'Tab Rilife', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-29', name: 'Drop metocolpramide', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Drop' },
  { id: 'man-30', name: 'Syringe', defaultStrength: '20ml', defaultInstructions: 'As directed', category: 'Equipment' },
  { id: 'man-31', name: 'Tab Phenazopyridine', defaultStrength: '100mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-32', name: 'Tab Tryptanol', defaultStrength: '25mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-33', name: 'Tab Ciprolife', defaultStrength: '500mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-34', name: 'Gloves Sterile', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Equipment' },
  { id: 'man-35', name: 'Cap Amoxicillin', defaultStrength: '500mg', defaultInstructions: 'As directed', category: 'Capsule' },
  { id: 'man-36', name: 'Syp Noacid', defaultStrength: '180mg', defaultInstructions: 'As directed', category: 'Syrup' },
  { id: 'man-37', name: 'Tab azetromycin', defaultStrength: '250mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-38', name: 'Cap omeprazol gastro', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Capsule' },
  { id: 'man-39', name: 'Tab colnazepam', defaultStrength: '1mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-40', name: 'Cap piroxicam', defaultStrength: '20mg', defaultInstructions: 'As directed', category: 'Capsule' },
  { id: 'man-41', name: 'Tab Levolife', defaultStrength: '500mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-42', name: 'Tab Famotidine', defaultStrength: '40mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-43', name: 'Amp Neurobion', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Ampule' },
  { id: 'man-44', name: 'Tab khoshe', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-45', name: 'Cap Rifampicin', defaultStrength: '300mg', defaultInstructions: 'As directed', category: 'Capsule' },
  { id: 'man-46', name: 'Cap Velosef', defaultStrength: '500mg', defaultInstructions: 'As directed', category: 'Capsule' },
  { id: 'man-47', name: 'Tab Pentolife-L', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-48', name: 'Syp Sucraheal', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Syrup' },
  { id: 'man-49', name: 'Amp Lasix', defaultStrength: '20mg', defaultInstructions: 'As directed', category: 'Ampule' },
  { id: 'man-50', name: 'Sachet Smecta', defaultStrength: '3G', defaultInstructions: 'As directed', category: 'Sachet' },
  { id: 'man-51', name: 'Tar Chromic', defaultStrength: '2/0', defaultInstructions: 'As directed', category: 'Tar' },
  { id: 'man-52', name: 'Johar joshanda', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Powder' },
  { id: 'man-53', name: 'Cap PAPZOLE -D', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Capsule' },
  { id: 'man-54', name: 'Tab amostat -t', defaultStrength: '5mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-55', name: 'Tab Mosegor', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-56', name: 'Tab Cachpar', defaultStrength: '500mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-57', name: 'Tab Cefixime', defaultStrength: '400mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-58', name: 'Syp septran DS', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Syrup' },
  { id: 'man-59', name: 'Cap M V', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Capsule' },
  { id: 'man-60', name: 'Tab escit a', defaultStrength: '10mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-61', name: 'Cap Omeprazole', defaultStrength: '40mg', defaultInstructions: 'As directed', category: 'Capsule' },
  { id: 'man-62', name: 'Cap Topdom', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Capsule' },
  { id: 'man-63', name: 'Tab jointcure', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-64', name: 'Cap Pento D', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Capsule' },
  { id: 'man-65', name: 'Vial Ceftriaxone life', defaultStrength: '1g', defaultInstructions: 'As directed', category: 'Vial' },
  { id: 'man-66', name: 'Amp Oxytocin', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Ampule' },
  { id: 'man-67', name: 'Tab Lemont A', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-68', name: 'Tab Metro-A', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-69', name: 'Tab sucraheal', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-70', name: 'Surgical Gass', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Equipment' },
  { id: 'man-71', name: 'Sir Ringer', defaultStrength: '500', defaultInstructions: 'As directed', category: 'Solution' },
  { id: 'man-72', name: 'Cap ACTILOSA', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Capsule' },
  { id: 'man-73', name: 'Cap Lansoprazol', defaultStrength: '30mg', defaultInstructions: 'As directed', category: 'Capsule' },
  { id: 'man-74', name: 'Tab Erect-on', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-75', name: 'Tab amtinol -a', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-76', name: 'Vial ciplacef', defaultStrength: '1gr', defaultInstructions: 'As directed', category: 'Vial' },
  { id: 'man-77', name: 'Tab bismuth', defaultStrength: '120mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-78', name: 'Tab septran DS', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-79', name: 'Sir rigar', defaultStrength: '1000ml', defaultInstructions: 'As directed', category: 'Solution' },
  { id: 'man-80', name: 'Amp Diclofenac', defaultStrength: '75', defaultInstructions: 'As directed', category: 'Ampule' },
  { id: 'man-81', name: 'Cap cefalexin', defaultStrength: '500mg', defaultInstructions: 'As directed', category: 'Capsule' },
  { id: 'man-82', name: 'Cap flovis', defaultStrength: '150mg', defaultInstructions: 'As directed', category: 'Capsule' },
  { id: 'man-83', name: 'Tab Parce-A', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-84', name: 'Cap tetracyclin', defaultStrength: '250mg', defaultInstructions: 'As directed', category: 'Capsule' },
  { id: 'man-85', name: 'Tab Inderal', defaultStrength: '10mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-86', name: 'Drop Xynosine', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Drop' },
  { id: 'man-87', name: 'Tab clonazepam', defaultStrength: '2mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-88', name: 'Tab vomilux', defaultStrength: '10mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-89', name: 'Cap lexat', defaultStrength: '60mg', defaultInstructions: 'As directed', category: 'Capsule' },
  { id: 'man-90', name: 'Cap gabamet -at', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Capsule' },
  { id: 'man-91', name: 'Tab Artimede', defaultStrength: '50mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-92', name: 'Amp Hyoscine', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Ampule' },
  { id: 'man-93', name: 'Tab NeuroBdoxine Puls', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-94', name: 'Tab Chymoral Forte', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-95', name: 'Tab Telmiyug-AM', defaultStrength: '40', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-96', name: 'Amp Gravinate', defaultStrength: '50mg', defaultInstructions: 'As directed', category: 'Ampule' },
  { id: 'man-97', name: 'Sir Normal saline', defaultStrength: '100', defaultInstructions: 'As directed', category: 'Solution' },
  { id: 'man-98', name: 'Tab Gravinate', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-99', name: 'Amp Magnesium Sulphate', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Ampule' },
  { id: 'man-100', name: 'Syp Eascof', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Syrup' },
  { id: 'man-101', name: 'Tab Amitriptyline', defaultStrength: '10mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-102', name: 'Tab Covance', defaultStrength: '5/160mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-103', name: 'Cap Celecoxib', defaultStrength: '200mg', defaultInstructions: 'As directed', category: 'Capsule' },
  { id: 'man-104', name: 'Amp Ketorolac', defaultStrength: '30mg', defaultInstructions: 'As directed', category: 'Ampule' },
  { id: 'man-105', name: 'Cap Doxycycline', defaultStrength: '100mg', defaultInstructions: 'As directed', category: 'Capsule' },
  { id: 'man-106', name: 'Tab calcium+vit d3', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-107', name: 'Syp Augmentin', defaultStrength: '156', defaultInstructions: 'As directed', category: 'Syrup' },
  { id: 'man-108', name: 'Amp Kenakort A', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Ampule' },
  { id: 'man-109', name: 'Tab Metformin', defaultStrength: '500mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-110', name: 'Vial pnz', defaultStrength: '40mg', defaultInstructions: 'As directed', category: 'Vial' },
  { id: 'man-111', name: 'Tab zapin- at', defaultStrength: '10mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-112', name: 'Syp cold aram', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Syrup' },
  { id: 'man-113', name: 'Tab Rosuvastatin', defaultStrength: '20', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-114', name: 'Tab Cetririzine', defaultStrength: '10mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-115', name: 'Tab Loratadine', defaultStrength: '10mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-116', name: 'Tab Nortriptyline', defaultStrength: '25mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-117', name: 'Tab Nortriptyline Hcl', defaultStrength: '25MG', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-118', name: 'Tab Erthromycine', defaultStrength: '250MG', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-119', name: 'Tab Norone N', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-120', name: 'Sir Mix', defaultStrength: '500', defaultInstructions: 'As directed', category: 'Solution' },
  { id: 'man-121', name: 'Tab Flagyl', defaultStrength: '400', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-122', name: 'Tab LD', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-123', name: 'Tab Nospa', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-124', name: 'Tab ABRA-D', defaultStrength: '100mg/60mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-125', name: 'Cap TUFCOLD', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Capsule' },
  { id: 'man-126', name: 'Cap Digestine', defaultStrength: '40mg', defaultInstructions: 'As directed', category: 'Capsule' },
  { id: 'man-127', name: 'Amp Gentamicin', defaultStrength: '20mg', defaultInstructions: 'As directed', category: 'Ampule' },
  { id: 'man-128', name: 'Syp Mucaine', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Syrup' },
  { id: 'man-129', name: 'Amp Betamethasone', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Ampule' },
  { id: 'man-130', name: 'Vial solocurtive', defaultStrength: '100mg', defaultInstructions: 'As directed', category: 'Vial' },
  { id: 'man-131', name: 'Cap R pride -A', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Capsule' },
  { id: 'man-132', name: 'Tab Spriamycin', defaultStrength: '500mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-133', name: 'Cap Fluoxetine', defaultStrength: '20mg', defaultInstructions: 'As directed', category: 'Capsule' },
  { id: 'man-134', name: 'Tab Prednisolone', defaultStrength: '5mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-135', name: 'Tab salbutamol', defaultStrength: '4mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-136', name: 'Tab mebendazole', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-137', name: 'Tab folic acid', defaultStrength: '5mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-138', name: 'Amp Ampicillin', defaultStrength: '1gr', defaultInstructions: 'As directed', category: 'Ampule' },
  { id: 'man-139', name: 'Sol ciprofloxacin', defaultStrength: '200mg', defaultInstructions: 'As directed', category: 'Solution' },
  { id: 'man-140', name: 'Syp Brufen DS', defaultStrength: '200mg', defaultInstructions: 'As directed', category: 'Syrup' },
  { id: 'man-141', name: 'Tab Metoclopramide', defaultStrength: '10mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-142', name: 'Tab Duphaston', defaultStrength: '10mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-143', name: 'Tab Sertraline', defaultStrength: '50mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-144', name: 'Tab Ofloxacine', defaultStrength: '200mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-145', name: 'Tab Acelo-P', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-146', name: 'Tab Dicycloverine', defaultStrength: '20mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-147', name: 'Tab Dexamethasone', defaultStrength: '0.5', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-148', name: 'Syp Cefix-A', defaultStrength: '200', defaultInstructions: 'As directed', category: 'Syrup' },
  { id: 'man-149', name: 'Syp Azetromycin', defaultStrength: '200mg', defaultInstructions: 'As directed', category: 'Syrup' },
  { id: 'man-150', name: 'Syp Ciprofloxacine', defaultStrength: '125mg', defaultInstructions: 'As directed', category: 'Syrup' },
  { id: 'man-151', name: 'Cap dexlansoprazole', defaultStrength: '60mg', defaultInstructions: 'As directed', category: 'Capsule' },
  { id: 'man-152', name: 'Tab cefixim', defaultStrength: '400 iran', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-153', name: 'Syp Metodine Df', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Syrup' },
  { id: 'man-154', name: 'Syp Snokast', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Syrup' },
  { id: 'man-155', name: 'Cap Omega 3', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Capsule' },
  { id: 'man-156', name: 'Syp SILCOL GEL', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Syrup' },
  { id: 'man-157', name: 'Cap RAB-L-AT', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Capsule' },
  { id: 'man-158', name: 'Syp Metoclopramid', defaultStrength: '5mg', defaultInstructions: 'As directed', category: 'Syrup' },
  { id: 'man-159', name: 'Tab Roviastatin atco', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-160', name: 'Cap Evion', defaultStrength: '400mg', defaultInstructions: 'As directed', category: 'Capsule' },
  { id: 'man-161', name: 'Syp OBH', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Syrup' },
  { id: 'man-162', name: 'Tab Vitamin B6', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-163', name: 'Cap Tranexamic Acid', defaultStrength: '250mg', defaultInstructions: 'As directed', category: 'Capsule' },
  { id: 'man-164', name: 'Tab HD', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-165', name: 'Tab Avil', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-166', name: 'Tab Albendazole', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-167', name: 'Cap Polybion', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Capsule' },
  { id: 'man-168', name: 'Tab Buscopan Plus', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-169', name: 'Tab Alprazolam', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-170', name: 'Tab Azetromycin', defaultStrength: '500mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-171', name: 'Syp Cetpro', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Syrup' },
  { id: 'man-172', name: 'Amp Trimadol', defaultStrength: '100mg', defaultInstructions: 'As directed', category: 'Ampule' },
  { id: 'man-173', name: 'Amp Maxolon', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Ampule' },
  { id: 'man-174', name: 'Amp Efedrin', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Ampule' },
  { id: 'man-175', name: 'Sol Betamethsone', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Solution' },
  { id: 'man-176', name: 'Tab cytopan', defaultStrength: '75mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-177', name: 'SYP Hemo ton s', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Syrup' },
  { id: 'man-178', name: 'Amp Testestro', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Ampule' },
  { id: 'man-179', name: 'Syp Albendazol', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Syrup' },
  { id: 'man-180', name: 'Syp Bronkal', defaultStrength: '2mg', defaultInstructions: 'As directed', category: 'Syrup' },
  { id: 'man-181', name: 'Amp neostijmine', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Ampule' },
  { id: 'man-182', name: 'Tab maxcold plus', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-183', name: 'Syp Health milk', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Syrup' },
  { id: 'man-184', name: 'Amp Mecobalamin', defaultStrength: '500mcg', defaultInstructions: 'As directed', category: 'Ampule' },
  { id: 'man-185', name: 'Tab Panadol', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-186', name: 'Cap mecobalamin', defaultStrength: '500mg', defaultInstructions: 'As directed', category: 'Capsule' },
  { id: 'man-187', name: 'Amp parcetamol', defaultStrength: '750 IM', defaultInstructions: 'As directed', category: 'Ampule' },
  { id: 'man-188', name: 'Cap M V+Ginsing', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Capsule' },
  { id: 'man-189', name: 'Amp atropin', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Ampule' },
  { id: 'man-190', name: 'Sir Polygeline', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Solution' },
  { id: 'man-191', name: 'Syp Neurozin', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Syrup' },
  { id: 'man-192', name: 'Syp Ginko B', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Syrup' },
  { id: 'man-193', name: 'Tab Ciprofloxacine', defaultStrength: '750mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-194', name: 'Tab Nifedipine', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-195', name: 'Tab Atenolol', defaultStrength: '50mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-196', name: 'Syp Ampiclox', defaultStrength: '250mg', defaultInstructions: 'As directed', category: 'Syrup' },
  { id: 'man-197', name: 'Syp Duphalac', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Syrup' },
  { id: 'man-198', name: 'Syp Trimetabol', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Syrup' },
  { id: 'man-199', name: 'Drop Nystatin', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Drop' },
  { id: 'man-200', name: 'Amp Bupicain', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Ampule' },
  { id: 'man-201', name: 'Tab gain UP', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-202', name: 'Vial bepan', defaultStrength: '40mg', defaultInstructions: 'As directed', category: 'Vial' },
  { id: 'man-203', name: 'Syp flajyl', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Syrup' },
  { id: 'man-204', name: 'Tab ansaid', defaultStrength: '100mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-205', name: 'Tab Atlide', defaultStrength: '40mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-206', name: 'Tab metronidazole', defaultStrength: '200mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-207', name: 'Tab gempid', defaultStrength: '600mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-208', name: 'Syp calprovit plus', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Syrup' },
  { id: 'man-209', name: 'Amp pancuronium', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Ampule' },
  { id: 'man-210', name: 'Amp suxemethonium', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Ampule' },
  { id: 'man-211', name: 'Vial propofol', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Vial' },
  { id: 'man-212', name: 'Cap cacid -E', defaultStrength: '40mg', defaultInstructions: 'As directed', category: 'Capsule' },
  { id: 'man-213', name: 'Tab Folic Acid', defaultStrength: '1mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-214', name: 'Syp Amoxil', defaultStrength: '125mg', defaultInstructions: 'As directed', category: 'Syrup' },
  { id: 'man-215', name: 'Syp Amoxil', defaultStrength: '250mg', defaultInstructions: 'As directed', category: 'Syrup' },
  { id: 'man-216', name: 'Tab ostorin', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-217', name: 'Drop Sodium chloride', defaultStrength: '0.9%', defaultInstructions: 'As directed', category: 'Drop' },
  { id: 'man-218', name: 'Drop vit D3', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Drop' },
  { id: 'man-219', name: 'Amp Gravibinan', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Ampule' },
  { id: 'man-220', name: 'Amp Tranexamic Acid', defaultStrength: '250mg', defaultInstructions: 'As directed', category: 'Ampule' },
  { id: 'man-221', name: 'Amp Paracetamol', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Ampule' },
  { id: 'man-222', name: 'Drop Sangkol', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Drop' },
  { id: 'man-223', name: 'Tab Augmentin', defaultStrength: '625mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-224', name: 'Syp Zinc', defaultStrength: '120ML', defaultInstructions: 'As directed', category: 'Syrup' },
  { id: 'man-225', name: 'Tab Diclocin fort', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-226', name: 'Tab Ciprofloxacin', defaultStrength: '250mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-227', name: 'Cap Fluconazole', defaultStrength: '150mg', defaultInstructions: 'As directed', category: 'Capsule' },
  { id: 'man-228', name: 'Tab Neoprox', defaultStrength: '500mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-229', name: 'Cap Sangobion', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Capsule' },
  { id: 'man-230', name: 'Tab Neurobion', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-231', name: 'Cap Cloxacillin', defaultStrength: '500mg', defaultInstructions: 'As directed', category: 'Capsule' },
  { id: 'man-232', name: 'Tab Clomifene', defaultStrength: '50mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-233', name: 'Tab Cipro A', defaultStrength: '500mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-234', name: 'Tab Spiromide-40', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-235', name: 'Tab Escitalopram', defaultStrength: '10mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-236', name: 'Syp Citralka', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Syrup' },
  { id: 'man-237', name: 'Drop Colicach', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Drop' },
  { id: 'man-238', name: 'Syp Brufen', defaultStrength: '100mg', defaultInstructions: 'As directed', category: 'Syrup' },
  { id: 'man-239', name: 'Tab Itoprid', defaultStrength: '50mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-240', name: 'Amp Progesterrone', defaultStrength: '50mg', defaultInstructions: 'As directed', category: 'Ampule' },
  { id: 'man-241', name: 'Amp Diazepam', defaultStrength: '10mg', defaultInstructions: 'As directed', category: 'Ampule' },
  { id: 'man-242', name: 'Syp probutic', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Syrup' },
  { id: 'man-243', name: 'Syp Cefadroxil', defaultStrength: '250mg', defaultInstructions: 'As directed', category: 'Syrup' },
  { id: 'man-244', name: 'Tab cabagrolin india', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-245', name: 'Tab b-cip', defaultStrength: '500mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-246', name: 'Tab paralif', defaultStrength: '500mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-247', name: 'Cap Gin xtra', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Capsule' },
  { id: 'man-248', name: 'Drop Otosporin', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Drop' },
  { id: 'man-249', name: 'Drop Skilax', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Drop' },
  { id: 'man-250', name: 'Syp Vermox', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Syrup' },
  { id: 'man-251', name: 'Sir cipesta DS', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Solution' },
  { id: 'man-252', name: 'Tab Sumoxen', defaultStrength: '85/500mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-253', name: 'Syp Domflash', defaultStrength: '5mg', defaultInstructions: 'As directed', category: 'Syrup' },
  { id: 'man-254', name: 'Tab cefixime', defaultStrength: '200mg iran', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-255', name: 'SYP STOGEST', defaultStrength: '240', defaultInstructions: 'As directed', category: 'Syrup' },
  { id: 'man-256', name: 'Syp INDOMAG', defaultStrength: '200ml', defaultInstructions: 'As directed', category: 'Syrup' },
  { id: 'man-257', name: 'Drop rocip -D', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Drop' },
  { id: 'man-258', name: 'Tab zinc', defaultStrength: '10mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-259', name: 'Amp HCG 5000 IND', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Ampule' },
  { id: 'man-260', name: 'Syp cal-d-at', defaultStrength: '200ml', defaultInstructions: 'As directed', category: 'Syrup' },
  { id: 'man-261', name: 'Vial ketamine', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Vial' },
  { id: 'man-262', name: 'Drop colorest', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Drop' },
  { id: 'man-263', name: 'Amp ferosoft A', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Ampule' },
  { id: 'man-264', name: 'Vial solocurtive', defaultStrength: '250mg', defaultInstructions: 'As directed', category: 'Vial' },
  { id: 'man-265', name: 'Amp Vitamin D3', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Ampule' },
  { id: 'man-266', name: 'Tab Lexotanil', defaultStrength: '3mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-267', name: 'Tab vitamim C', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-268', name: 'Tab Folic Acid', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-269', name: 'Tab Rifaxa', defaultStrength: '550mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-270', name: 'Tab Mebeverine', defaultStrength: '135mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-271', name: 'Tab Tinidazole', defaultStrength: '500mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-272', name: 'Tab Dine 35', defaultStrength: 'N/A', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-273', name: 'Tab Estraiol', defaultStrength: '1mg', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-274', name: 'Tab Methyldopa', defaultStrength: '250', defaultInstructions: 'As directed', category: 'Tablet' },
  { id: 'man-275', name: 'Cap Pregabalin', defaultStrength: '75mg', defaultInstructions: 'As directed', category: 'Capsule' }
];

export const ICD_DIAGNOSES: DiagnosisTemplate[] = [
  { code: 'A09', title: 'Acute diarrhea and gastroenteritis', category: 'Gastrointestinal' },
  { code: 'A01', title: 'Typhoid and paratyphoid fevers', category: 'Infectious' },
  { code: 'E11.9', title: 'Type 2 diabetes mellitus without complications', category: 'Endocrine' },
  { code: 'I10', title: 'Essential (primary) hypertension', category: 'Cardiology' },
  { code: 'J00', title: 'Acute nasopharyngitis (Common cold)', category: 'Respiratory' },
  { code: 'J45.9', title: 'Asthma, unspecified', category: 'Respiratory' },
  { code: 'N39.0', title: 'Urinary tract infection, site not specified', category: 'Genitourinary' },
  { code: 'M54.5', title: 'Low back pain', category: 'Orthopaedic' }
];

export const DEFAULT_CLINIC_SETTINGS: ClinicSettings = {
  name: 'کلینیک تخصصی معالجوی آریانا',
  doctor: 'داکتر احمد فرید صدیقی',
  specialty: 'متخصص امراض داخله عمومی و جراحی',
  address: 'کابل، چهارراهی صدارت، کابل - افغانستان',
  phone: '۰۷۸۸۸۸۸۸۸۸ / ۰۷۹۹۹۹۹۹۹۹',
  tagline: 'تداوی با استندردهای جهانی و مراقبت‌های ویژه',
  language: 'fa',
  printLayout: {
    pageSize: 'A4',
    showPatientName: true,
    showAge: true,
    showWeight: true,
    showDate: true,
    showBP: true,
    showPulse: true,
    showResp: true,
    showTemp: true,
    showDiagnosis: true,
    showDrugList: true,
  }
};